/*
Anchore Experimental API

Testing SBOMManagementAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package experimental

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/anchore/enterprise-client-go"
)

func Test_experimental_SBOMManagementAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SBOMManagementAPIService AddSbom", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SBOMManagementAPI.AddSbom(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService BulkModifySbomGroupMemberships", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SBOMManagementAPI.BulkModifySbomGroupMemberships(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService CreateSbomGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SBOMManagementAPI.CreateSbomGroup(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService DeleteSbom", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string

		httpRes, err := apiClient.SBOMManagementAPI.DeleteSbom(context.Background(), sbomUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService DeleteSbomGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupUuid string

		httpRes, err := apiClient.SBOMManagementAPI.DeleteSbomGroup(context.Background(), groupUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService DeleteSbomRevision", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string
		var revisionUuid string

		httpRes, err := apiClient.SBOMManagementAPI.DeleteSbomRevision(context.Background(), sbomUuid, revisionUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService GetLatestSbomByUuid", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.GetLatestSbomByUuid(context.Background(), sbomUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService GetLatestSbomPackagesByUuid", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.GetLatestSbomPackagesByUuid(context.Background(), sbomUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService GetSbomFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.GetSbomFile(context.Background(), sbomUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService GetSbomGroupByUuid", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.GetSbomGroupByUuid(context.Background(), groupUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService GetSbomGroupVulnerabilitiesCsv", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.GetSbomGroupVulnerabilitiesCsv(context.Background(), groupUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService GetSbomGroupZip", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.GetSbomGroupZip(context.Background(), groupUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService GetSbomRevision", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string
		var revisionUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.GetSbomRevision(context.Background(), sbomUuid, revisionUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService GetSbomRevisionFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string
		var revisionUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.GetSbomRevisionFile(context.Background(), sbomUuid, revisionUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService GetSbomVulnerabilitiesCsv", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.GetSbomVulnerabilitiesCsv(context.Background(), sbomUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService ListSbomGroupVulnerabilities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.ListSbomGroupVulnerabilities(context.Background(), groupUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService ListSbomGroups", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SBOMManagementAPI.ListSbomGroups(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService ListSbomVulnerabilities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.ListSbomVulnerabilities(context.Background(), sbomUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService ListSboms", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SBOMManagementAPI.ListSboms(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService ModifySbomGroupMemberships", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.ModifySbomGroupMemberships(context.Background(), groupUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService PatchSbom", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.PatchSbom(context.Background(), sbomUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService PutSbom", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sbomUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.PutSbom(context.Background(), sbomUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SBOMManagementAPIService UpdateSbomGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupUuid string

		resp, httpRes, err := apiClient.SBOMManagementAPI.UpdateSbomGroup(context.Background(), groupUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
