/*
Anchore Engine API Server

This is the Anchore Engine API. Provides the primary external API for users of the service.

API version: 0.6.0
Contact: nurmi@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package engine

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
)

// Linger please
var (
	_ _context.Context
)

type RepositoryCredentialsApi interface {

	/*
	AddRepository Add repository to watch

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @return ApiAddRepositoryRequest
	*/
	AddRepository(ctx _context.Context) ApiAddRepositoryRequest

	// AddRepositoryExecute executes the request
	//  @return []Subscription
	AddRepositoryExecute(r ApiAddRepositoryRequest) ([]Subscription, *_nethttp.Response, error)
}

// RepositoryCredentialsApiService RepositoryCredentialsApi service
type RepositoryCredentialsApiService service

type ApiAddRepositoryRequest struct {
	ctx _context.Context
	ApiService RepositoryCredentialsApi
	repository *string
	autoSubscribe *bool
	dryRun *bool
	xAnchoreAccount *string
}

// full repository to add e.g. docker.io/library/alpine
func (r ApiAddRepositoryRequest) Repository(repository string) ApiAddRepositoryRequest {
	r.repository = &repository
	return r
}
// flag to enable/disable auto tag_update activation when new images from a repo are added
func (r ApiAddRepositoryRequest) AutoSubscribe(autoSubscribe bool) ApiAddRepositoryRequest {
	r.autoSubscribe = &autoSubscribe
	return r
}
// flag to return tags in the repository without actually watching the repository, default is false
func (r ApiAddRepositoryRequest) DryRun(dryRun bool) ApiAddRepositoryRequest {
	r.dryRun = &dryRun
	return r
}
// An account name to change the resource scope of the request to that account, if permissions allow (admin only)
func (r ApiAddRepositoryRequest) XAnchoreAccount(xAnchoreAccount string) ApiAddRepositoryRequest {
	r.xAnchoreAccount = &xAnchoreAccount
	return r
}

func (r ApiAddRepositoryRequest) Execute() ([]Subscription, *_nethttp.Response, error) {
	return r.ApiService.AddRepositoryExecute(r)
}

/*
AddRepository Add repository to watch

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAddRepositoryRequest
*/
func (a *RepositoryCredentialsApiService) AddRepository(ctx _context.Context) ApiAddRepositoryRequest {
	return ApiAddRepositoryRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []Subscription
func (a *RepositoryCredentialsApiService) AddRepositoryExecute(r ApiAddRepositoryRequest) ([]Subscription, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  []Subscription
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RepositoryCredentialsApiService.AddRepository")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/repositories"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.repository == nil {
		return localVarReturnValue, nil, reportError("repository is required and must be specified")
	}

	localVarQueryParams.Add("repository", parameterToString(*r.repository, ""))
	if r.autoSubscribe != nil {
		localVarQueryParams.Add("auto_subscribe", parameterToString(*r.autoSubscribe, ""))
	}
	if r.dryRun != nil {
		localVarQueryParams.Add("dry_run", parameterToString(*r.dryRun, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xAnchoreAccount != nil {
		localVarHeaderParams["x-anchore-account"] = parameterToString(*r.xAnchoreAccount, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
