/*
Anchore API

This is the Anchore API. Provides the external API for users of Anchore Enterprise.

API version: 2.13.0
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package enterprise

import (
	"encoding/json"
	"fmt"
)

// checks if the FileContents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileContents{}

// FileContents struct for FileContents
type FileContents struct {
	// The media type of this result
	MediaType string `json:"media_type"`
	Metadata FileContentsMetadata `json:"metadata"`
	Findings []FileContentsFindingsInner `json:"findings"`
	AdditionalProperties map[string]interface{}
}

type _FileContents FileContents

// NewFileContents instantiates a new FileContents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileContents(mediaType string, metadata FileContentsMetadata, findings []FileContentsFindingsInner) *FileContents {
	this := FileContents{}
	this.MediaType = mediaType
	this.Metadata = metadata
	this.Findings = findings
	return &this
}

// NewFileContentsWithDefaults instantiates a new FileContents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileContentsWithDefaults() *FileContents {
	this := FileContents{}
	return &this
}

// GetMediaType returns the MediaType field value
func (o *FileContents) GetMediaType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MediaType
}

// GetMediaTypeOk returns a tuple with the MediaType field value
// and a boolean to check if the value has been set.
func (o *FileContents) GetMediaTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MediaType, true
}

// SetMediaType sets field value
func (o *FileContents) SetMediaType(v string) {
	o.MediaType = v
}

// GetMetadata returns the Metadata field value
func (o *FileContents) GetMetadata() FileContentsMetadata {
	if o == nil {
		var ret FileContentsMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *FileContents) GetMetadataOk() (*FileContentsMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *FileContents) SetMetadata(v FileContentsMetadata) {
	o.Metadata = v
}

// GetFindings returns the Findings field value
func (o *FileContents) GetFindings() []FileContentsFindingsInner {
	if o == nil {
		var ret []FileContentsFindingsInner
		return ret
	}

	return o.Findings
}

// GetFindingsOk returns a tuple with the Findings field value
// and a boolean to check if the value has been set.
func (o *FileContents) GetFindingsOk() ([]FileContentsFindingsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Findings, true
}

// SetFindings sets field value
func (o *FileContents) SetFindings(v []FileContentsFindingsInner) {
	o.Findings = v
}

func (o FileContents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileContents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["media_type"] = o.MediaType
	toSerialize["metadata"] = o.Metadata
	toSerialize["findings"] = o.Findings

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FileContents) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"media_type",
		"metadata",
		"findings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileContents := _FileContents{}

	err = json.Unmarshal(data, &varFileContents)

	if err != nil {
		return err
	}

	*o = FileContents(varFileContents)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "media_type")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "findings")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFileContents struct {
	value *FileContents
	isSet bool
}

func (v NullableFileContents) Get() *FileContents {
	return v.value
}

func (v *NullableFileContents) Set(val *FileContents) {
	v.value = val
	v.isSet = true
}

func (v NullableFileContents) IsSet() bool {
	return v.isSet
}

func (v *NullableFileContents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileContents(val *FileContents) *NullableFileContents {
	return &NullableFileContents{value: val, isSet: true}
}

func (v NullableFileContents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileContents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


