/*
Anchore API

This is the Anchore API. Provides the external API for users of Anchore Enterprise.

API version: 2.12.1
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package enterprise

import (
	"encoding/json"
	"time"
)

// checks if the PackageEPSS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PackageEPSS{}

// PackageEPSS struct for PackageEPSS
type PackageEPSS struct {
	Cve *string `json:"cve,omitempty"`
	Date *time.Time `json:"date,omitempty"`
	Epss *float32 `json:"epss,omitempty"`
	Percentile *float32 `json:"percentile,omitempty"`
}

// NewPackageEPSS instantiates a new PackageEPSS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackageEPSS() *PackageEPSS {
	this := PackageEPSS{}
	return &this
}

// NewPackageEPSSWithDefaults instantiates a new PackageEPSS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackageEPSSWithDefaults() *PackageEPSS {
	this := PackageEPSS{}
	return &this
}

// GetCve returns the Cve field value if set, zero value otherwise.
func (o *PackageEPSS) GetCve() string {
	if o == nil || IsNil(o.Cve) {
		var ret string
		return ret
	}
	return *o.Cve
}

// GetCveOk returns a tuple with the Cve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageEPSS) GetCveOk() (*string, bool) {
	if o == nil || IsNil(o.Cve) {
		return nil, false
	}
	return o.Cve, true
}

// HasCve returns a boolean if a field has been set.
func (o *PackageEPSS) HasCve() bool {
	if o != nil && !IsNil(o.Cve) {
		return true
	}

	return false
}

// SetCve gets a reference to the given string and assigns it to the Cve field.
func (o *PackageEPSS) SetCve(v string) {
	o.Cve = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *PackageEPSS) GetDate() time.Time {
	if o == nil || IsNil(o.Date) {
		var ret time.Time
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageEPSS) GetDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *PackageEPSS) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given time.Time and assigns it to the Date field.
func (o *PackageEPSS) SetDate(v time.Time) {
	o.Date = &v
}

// GetEpss returns the Epss field value if set, zero value otherwise.
func (o *PackageEPSS) GetEpss() float32 {
	if o == nil || IsNil(o.Epss) {
		var ret float32
		return ret
	}
	return *o.Epss
}

// GetEpssOk returns a tuple with the Epss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageEPSS) GetEpssOk() (*float32, bool) {
	if o == nil || IsNil(o.Epss) {
		return nil, false
	}
	return o.Epss, true
}

// HasEpss returns a boolean if a field has been set.
func (o *PackageEPSS) HasEpss() bool {
	if o != nil && !IsNil(o.Epss) {
		return true
	}

	return false
}

// SetEpss gets a reference to the given float32 and assigns it to the Epss field.
func (o *PackageEPSS) SetEpss(v float32) {
	o.Epss = &v
}

// GetPercentile returns the Percentile field value if set, zero value otherwise.
func (o *PackageEPSS) GetPercentile() float32 {
	if o == nil || IsNil(o.Percentile) {
		var ret float32
		return ret
	}
	return *o.Percentile
}

// GetPercentileOk returns a tuple with the Percentile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackageEPSS) GetPercentileOk() (*float32, bool) {
	if o == nil || IsNil(o.Percentile) {
		return nil, false
	}
	return o.Percentile, true
}

// HasPercentile returns a boolean if a field has been set.
func (o *PackageEPSS) HasPercentile() bool {
	if o != nil && !IsNil(o.Percentile) {
		return true
	}

	return false
}

// SetPercentile gets a reference to the given float32 and assigns it to the Percentile field.
func (o *PackageEPSS) SetPercentile(v float32) {
	o.Percentile = &v
}

func (o PackageEPSS) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PackageEPSS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cve) {
		toSerialize["cve"] = o.Cve
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Epss) {
		toSerialize["epss"] = o.Epss
	}
	if !IsNil(o.Percentile) {
		toSerialize["percentile"] = o.Percentile
	}
	return toSerialize, nil
}

type NullablePackageEPSS struct {
	value *PackageEPSS
	isSet bool
}

func (v NullablePackageEPSS) Get() *PackageEPSS {
	return v.value
}

func (v *NullablePackageEPSS) Set(val *PackageEPSS) {
	v.value = val
	v.isSet = true
}

func (v NullablePackageEPSS) IsSet() bool {
	return v.isSet
}

func (v *NullablePackageEPSS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackageEPSS(val *PackageEPSS) *NullablePackageEPSS {
	return &NullablePackageEPSS{value: val, isSet: true}
}

func (v NullablePackageEPSS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackageEPSS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


