/*
Anchore Enterprise API Server

This is the Anchore Enterprise API. It provides additional external API routes and functionality for enterprise users.

API version: 0.2.1
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package enterprise

import (
	"encoding/json"
)

// SbomDiff The diff of two sboms with context applied in each difference. Includes the content of both sboms fully
type SbomDiff struct {
	Added *[]interface{} `json:"added,omitempty"`
	Removed *[]interface{} `json:"removed,omitempty"`
	Modified *[]interface{} `json:"modified,omitempty"`
	Unmodified *[]interface{} `json:"unmodified,omitempty"`
}

// NewSbomDiff instantiates a new SbomDiff object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSbomDiff() *SbomDiff {
	this := SbomDiff{}
	return &this
}

// NewSbomDiffWithDefaults instantiates a new SbomDiff object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSbomDiffWithDefaults() *SbomDiff {
	this := SbomDiff{}
	return &this
}

// GetAdded returns the Added field value if set, zero value otherwise.
func (o *SbomDiff) GetAdded() []interface{} {
	if o == nil || o.Added == nil {
		var ret []interface{}
		return ret
	}
	return *o.Added
}

// GetAddedOk returns a tuple with the Added field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SbomDiff) GetAddedOk() (*[]interface{}, bool) {
	if o == nil || o.Added == nil {
		return nil, false
	}
	return o.Added, true
}

// HasAdded returns a boolean if a field has been set.
func (o *SbomDiff) HasAdded() bool {
	if o != nil && o.Added != nil {
		return true
	}

	return false
}

// SetAdded gets a reference to the given []interface{} and assigns it to the Added field.
func (o *SbomDiff) SetAdded(v []interface{}) {
	o.Added = &v
}

// GetRemoved returns the Removed field value if set, zero value otherwise.
func (o *SbomDiff) GetRemoved() []interface{} {
	if o == nil || o.Removed == nil {
		var ret []interface{}
		return ret
	}
	return *o.Removed
}

// GetRemovedOk returns a tuple with the Removed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SbomDiff) GetRemovedOk() (*[]interface{}, bool) {
	if o == nil || o.Removed == nil {
		return nil, false
	}
	return o.Removed, true
}

// HasRemoved returns a boolean if a field has been set.
func (o *SbomDiff) HasRemoved() bool {
	if o != nil && o.Removed != nil {
		return true
	}

	return false
}

// SetRemoved gets a reference to the given []interface{} and assigns it to the Removed field.
func (o *SbomDiff) SetRemoved(v []interface{}) {
	o.Removed = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *SbomDiff) GetModified() []interface{} {
	if o == nil || o.Modified == nil {
		var ret []interface{}
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SbomDiff) GetModifiedOk() (*[]interface{}, bool) {
	if o == nil || o.Modified == nil {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *SbomDiff) HasModified() bool {
	if o != nil && o.Modified != nil {
		return true
	}

	return false
}

// SetModified gets a reference to the given []interface{} and assigns it to the Modified field.
func (o *SbomDiff) SetModified(v []interface{}) {
	o.Modified = &v
}

// GetUnmodified returns the Unmodified field value if set, zero value otherwise.
func (o *SbomDiff) GetUnmodified() []interface{} {
	if o == nil || o.Unmodified == nil {
		var ret []interface{}
		return ret
	}
	return *o.Unmodified
}

// GetUnmodifiedOk returns a tuple with the Unmodified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SbomDiff) GetUnmodifiedOk() (*[]interface{}, bool) {
	if o == nil || o.Unmodified == nil {
		return nil, false
	}
	return o.Unmodified, true
}

// HasUnmodified returns a boolean if a field has been set.
func (o *SbomDiff) HasUnmodified() bool {
	if o != nil && o.Unmodified != nil {
		return true
	}

	return false
}

// SetUnmodified gets a reference to the given []interface{} and assigns it to the Unmodified field.
func (o *SbomDiff) SetUnmodified(v []interface{}) {
	o.Unmodified = &v
}

func (o SbomDiff) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Added != nil {
		toSerialize["added"] = o.Added
	}
	if o.Removed != nil {
		toSerialize["removed"] = o.Removed
	}
	if o.Modified != nil {
		toSerialize["modified"] = o.Modified
	}
	if o.Unmodified != nil {
		toSerialize["unmodified"] = o.Unmodified
	}
	return json.Marshal(toSerialize)
}

type NullableSbomDiff struct {
	value *SbomDiff
	isSet bool
}

func (v NullableSbomDiff) Get() *SbomDiff {
	return v.value
}

func (v *NullableSbomDiff) Set(val *SbomDiff) {
	v.value = val
	v.isSet = true
}

func (v NullableSbomDiff) IsSet() bool {
	return v.isSet
}

func (v *NullableSbomDiff) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSbomDiff(val *SbomDiff) *NullableSbomDiff {
	return &NullableSbomDiff{value: val, isSet: true}
}

func (v NullableSbomDiff) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSbomDiff) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


