/*
Anchore API

This is the Anchore API. Provides the external API for users of Anchore Enterprise.

API version: 2.10.2
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package enterprise

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// SystemConfigurationValueOneOfInner - struct for SystemConfigurationValueOneOfInner
type SystemConfigurationValueOneOfInner struct {
	Int32 *int32
	Any *interface{}
	String *string
}

// int32AsSystemConfigurationValueOneOfInner is a convenience function that returns int32 wrapped in SystemConfigurationValueOneOfInner
func Int32AsSystemConfigurationValueOneOfInner(v *int32) SystemConfigurationValueOneOfInner {
	return SystemConfigurationValueOneOfInner{
		Int32: v,
	}
}

// interface{}AsSystemConfigurationValueOneOfInner is a convenience function that returns interface{} wrapped in SystemConfigurationValueOneOfInner
func AnyAsSystemConfigurationValueOneOfInner(v *interface{}) SystemConfigurationValueOneOfInner {
	return SystemConfigurationValueOneOfInner{
		Any: v,
	}
}

// stringAsSystemConfigurationValueOneOfInner is a convenience function that returns string wrapped in SystemConfigurationValueOneOfInner
func StringAsSystemConfigurationValueOneOfInner(v *string) SystemConfigurationValueOneOfInner {
	return SystemConfigurationValueOneOfInner{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SystemConfigurationValueOneOfInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into Any
	err = newStrictDecoder(data).Decode(&dst.Any)
	if err == nil {
		jsonAny, _ := json.Marshal(dst.Any)
		if string(jsonAny) == "{}" { // empty struct
			dst.Any = nil
		} else {
			if err = validator.Validate(dst.Any); err != nil {
				dst.Any = nil
			} else {
				match++
			}
		}
	} else {
		dst.Any = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int32 = nil
		dst.Any = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SystemConfigurationValueOneOfInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SystemConfigurationValueOneOfInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SystemConfigurationValueOneOfInner) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.Any != nil {
		return json.Marshal(&src.Any)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SystemConfigurationValueOneOfInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.Any != nil {
		return obj.Any
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableSystemConfigurationValueOneOfInner struct {
	value *SystemConfigurationValueOneOfInner
	isSet bool
}

func (v NullableSystemConfigurationValueOneOfInner) Get() *SystemConfigurationValueOneOfInner {
	return v.value
}

func (v *NullableSystemConfigurationValueOneOfInner) Set(val *SystemConfigurationValueOneOfInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemConfigurationValueOneOfInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemConfigurationValueOneOfInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemConfigurationValueOneOfInner(val *SystemConfigurationValueOneOfInner) *NullableSystemConfigurationValueOneOfInner {
	return &NullableSystemConfigurationValueOneOfInner{value: val, isSet: true}
}

func (v NullableSystemConfigurationValueOneOfInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemConfigurationValueOneOfInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


