/*
Anchore API

This is the Anchore API. Provides the external API for users of Anchore Enterprise.

API version: 2.0.0
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package enterprise

import (
	"encoding/json"
)

// ECSServicesServicesInner struct for ECSServicesServicesInner
type ECSServicesServicesInner struct {
	Arn string `json:"arn"`
	ClusterArn string `json:"cluster_arn"`
	Tags map[string]string `json:"tags"`
	AccountName string `json:"account_name"`
}

// NewECSServicesServicesInner instantiates a new ECSServicesServicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewECSServicesServicesInner(arn string, clusterArn string, tags map[string]string, accountName string) *ECSServicesServicesInner {
	this := ECSServicesServicesInner{}
	this.Arn = arn
	this.ClusterArn = clusterArn
	this.Tags = tags
	this.AccountName = accountName
	return &this
}

// NewECSServicesServicesInnerWithDefaults instantiates a new ECSServicesServicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewECSServicesServicesInnerWithDefaults() *ECSServicesServicesInner {
	this := ECSServicesServicesInner{}
	return &this
}

// GetArn returns the Arn field value
func (o *ECSServicesServicesInner) GetArn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Arn
}

// GetArnOk returns a tuple with the Arn field value
// and a boolean to check if the value has been set.
func (o *ECSServicesServicesInner) GetArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Arn, true
}

// SetArn sets field value
func (o *ECSServicesServicesInner) SetArn(v string) {
	o.Arn = v
}

// GetClusterArn returns the ClusterArn field value
func (o *ECSServicesServicesInner) GetClusterArn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterArn
}

// GetClusterArnOk returns a tuple with the ClusterArn field value
// and a boolean to check if the value has been set.
func (o *ECSServicesServicesInner) GetClusterArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterArn, true
}

// SetClusterArn sets field value
func (o *ECSServicesServicesInner) SetClusterArn(v string) {
	o.ClusterArn = v
}

// GetTags returns the Tags field value
func (o *ECSServicesServicesInner) GetTags() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *ECSServicesServicesInner) GetTagsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *ECSServicesServicesInner) SetTags(v map[string]string) {
	o.Tags = v
}

// GetAccountName returns the AccountName field value
func (o *ECSServicesServicesInner) GetAccountName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value
// and a boolean to check if the value has been set.
func (o *ECSServicesServicesInner) GetAccountNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountName, true
}

// SetAccountName sets field value
func (o *ECSServicesServicesInner) SetAccountName(v string) {
	o.AccountName = v
}

func (o ECSServicesServicesInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["arn"] = o.Arn
	}
	if true {
		toSerialize["cluster_arn"] = o.ClusterArn
	}
	if true {
		toSerialize["tags"] = o.Tags
	}
	if true {
		toSerialize["account_name"] = o.AccountName
	}
	return json.Marshal(toSerialize)
}

type NullableECSServicesServicesInner struct {
	value *ECSServicesServicesInner
	isSet bool
}

func (v NullableECSServicesServicesInner) Get() *ECSServicesServicesInner {
	return v.value
}

func (v *NullableECSServicesServicesInner) Set(val *ECSServicesServicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableECSServicesServicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableECSServicesServicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableECSServicesServicesInner(val *ECSServicesServicesInner) *NullableECSServicesServicesInner {
	return &NullableECSServicesServicesInner{value: val, isSet: true}
}

func (v NullableECSServicesServicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableECSServicesServicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


