/*
Anchore API

This is the Anchore API. Provides the external API for users of Anchore Enterprise.

API version: 2.7.2
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package enterprise

import (
	"encoding/json"
)

// EventResponseEventSource struct for EventResponseEventSource
type EventResponseEventSource struct {
	ServiceName *string `json:"service_name,omitempty"`
	HostId *string `json:"host_id,omitempty"`
	BaseUrl *string `json:"base_url,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// NewEventResponseEventSource instantiates a new EventResponseEventSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventResponseEventSource() *EventResponseEventSource {
	this := EventResponseEventSource{}
	return &this
}

// NewEventResponseEventSourceWithDefaults instantiates a new EventResponseEventSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventResponseEventSourceWithDefaults() *EventResponseEventSource {
	this := EventResponseEventSource{}
	return &this
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *EventResponseEventSource) GetServiceName() string {
	if o == nil || o.ServiceName == nil {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventResponseEventSource) GetServiceNameOk() (*string, bool) {
	if o == nil || o.ServiceName == nil {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *EventResponseEventSource) HasServiceName() bool {
	if o != nil && o.ServiceName != nil {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *EventResponseEventSource) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetHostId returns the HostId field value if set, zero value otherwise.
func (o *EventResponseEventSource) GetHostId() string {
	if o == nil || o.HostId == nil {
		var ret string
		return ret
	}
	return *o.HostId
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventResponseEventSource) GetHostIdOk() (*string, bool) {
	if o == nil || o.HostId == nil {
		return nil, false
	}
	return o.HostId, true
}

// HasHostId returns a boolean if a field has been set.
func (o *EventResponseEventSource) HasHostId() bool {
	if o != nil && o.HostId != nil {
		return true
	}

	return false
}

// SetHostId gets a reference to the given string and assigns it to the HostId field.
func (o *EventResponseEventSource) SetHostId(v string) {
	o.HostId = &v
}

// GetBaseUrl returns the BaseUrl field value if set, zero value otherwise.
func (o *EventResponseEventSource) GetBaseUrl() string {
	if o == nil || o.BaseUrl == nil {
		var ret string
		return ret
	}
	return *o.BaseUrl
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventResponseEventSource) GetBaseUrlOk() (*string, bool) {
	if o == nil || o.BaseUrl == nil {
		return nil, false
	}
	return o.BaseUrl, true
}

// HasBaseUrl returns a boolean if a field has been set.
func (o *EventResponseEventSource) HasBaseUrl() bool {
	if o != nil && o.BaseUrl != nil {
		return true
	}

	return false
}

// SetBaseUrl gets a reference to the given string and assigns it to the BaseUrl field.
func (o *EventResponseEventSource) SetBaseUrl(v string) {
	o.BaseUrl = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *EventResponseEventSource) GetRequestId() string {
	if o == nil || o.RequestId == nil {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventResponseEventSource) GetRequestIdOk() (*string, bool) {
	if o == nil || o.RequestId == nil {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *EventResponseEventSource) HasRequestId() bool {
	if o != nil && o.RequestId != nil {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *EventResponseEventSource) SetRequestId(v string) {
	o.RequestId = &v
}

func (o EventResponseEventSource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ServiceName != nil {
		toSerialize["service_name"] = o.ServiceName
	}
	if o.HostId != nil {
		toSerialize["host_id"] = o.HostId
	}
	if o.BaseUrl != nil {
		toSerialize["base_url"] = o.BaseUrl
	}
	if o.RequestId != nil {
		toSerialize["request_id"] = o.RequestId
	}
	return json.Marshal(toSerialize)
}

type NullableEventResponseEventSource struct {
	value *EventResponseEventSource
	isSet bool
}

func (v NullableEventResponseEventSource) Get() *EventResponseEventSource {
	return v.value
}

func (v *NullableEventResponseEventSource) Set(val *EventResponseEventSource) {
	v.value = val
	v.isSet = true
}

func (v NullableEventResponseEventSource) IsSet() bool {
	return v.isSet
}

func (v *NullableEventResponseEventSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventResponseEventSource(val *EventResponseEventSource) *NullableEventResponseEventSource {
	return &NullableEventResponseEventSource{value: val, isSet: true}
}

func (v NullableEventResponseEventSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventResponseEventSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


