/*
Anchore API

This is the Anchore API. Provides the external API for users of Anchore Enterprise.

API version: 2.5.0
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package enterprise

import (
	"encoding/json"
)

// UserGroupRolePost struct for UserGroupRolePost
type UserGroupRolePost struct {
	// The account
	ForAccount string `json:"for_account"`
	Roles []UserGroupRolePostRolesInner `json:"roles"`
}

// NewUserGroupRolePost instantiates a new UserGroupRolePost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGroupRolePost(forAccount string, roles []UserGroupRolePostRolesInner) *UserGroupRolePost {
	this := UserGroupRolePost{}
	this.ForAccount = forAccount
	this.Roles = roles
	return &this
}

// NewUserGroupRolePostWithDefaults instantiates a new UserGroupRolePost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGroupRolePostWithDefaults() *UserGroupRolePost {
	this := UserGroupRolePost{}
	return &this
}

// GetForAccount returns the ForAccount field value
func (o *UserGroupRolePost) GetForAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ForAccount
}

// GetForAccountOk returns a tuple with the ForAccount field value
// and a boolean to check if the value has been set.
func (o *UserGroupRolePost) GetForAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ForAccount, true
}

// SetForAccount sets field value
func (o *UserGroupRolePost) SetForAccount(v string) {
	o.ForAccount = v
}

// GetRoles returns the Roles field value
func (o *UserGroupRolePost) GetRoles() []UserGroupRolePostRolesInner {
	if o == nil {
		var ret []UserGroupRolePostRolesInner
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *UserGroupRolePost) GetRolesOk() ([]UserGroupRolePostRolesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *UserGroupRolePost) SetRoles(v []UserGroupRolePostRolesInner) {
	o.Roles = v
}

func (o UserGroupRolePost) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["for_account"] = o.ForAccount
	}
	if true {
		toSerialize["roles"] = o.Roles
	}
	return json.Marshal(toSerialize)
}

type NullableUserGroupRolePost struct {
	value *UserGroupRolePost
	isSet bool
}

func (v NullableUserGroupRolePost) Get() *UserGroupRolePost {
	return v.value
}

func (v *NullableUserGroupRolePost) Set(val *UserGroupRolePost) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGroupRolePost) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGroupRolePost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGroupRolePost(val *UserGroupRolePost) *NullableUserGroupRolePost {
	return &NullableUserGroupRolePost{value: val, isSet: true}
}

func (v NullableUserGroupRolePost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGroupRolePost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


