/*
Anchore API

This is the Anchore API. Provides the external API for users of Anchore Enterprise.

API version: 2.2.0
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package enterprise

import (
	"encoding/json"
)

// RbacManagerIdpUserGroupPost struct for RbacManagerIdpUserGroupPost
type RbacManagerIdpUserGroupPost struct {
	UserGroups []string `json:"user_groups,omitempty"`
}

// NewRbacManagerIdpUserGroupPost instantiates a new RbacManagerIdpUserGroupPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRbacManagerIdpUserGroupPost() *RbacManagerIdpUserGroupPost {
	this := RbacManagerIdpUserGroupPost{}
	return &this
}

// NewRbacManagerIdpUserGroupPostWithDefaults instantiates a new RbacManagerIdpUserGroupPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRbacManagerIdpUserGroupPostWithDefaults() *RbacManagerIdpUserGroupPost {
	this := RbacManagerIdpUserGroupPost{}
	return &this
}

// GetUserGroups returns the UserGroups field value if set, zero value otherwise.
func (o *RbacManagerIdpUserGroupPost) GetUserGroups() []string {
	if o == nil || o.UserGroups == nil {
		var ret []string
		return ret
	}
	return o.UserGroups
}

// GetUserGroupsOk returns a tuple with the UserGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RbacManagerIdpUserGroupPost) GetUserGroupsOk() ([]string, bool) {
	if o == nil || o.UserGroups == nil {
		return nil, false
	}
	return o.UserGroups, true
}

// HasUserGroups returns a boolean if a field has been set.
func (o *RbacManagerIdpUserGroupPost) HasUserGroups() bool {
	if o != nil && o.UserGroups != nil {
		return true
	}

	return false
}

// SetUserGroups gets a reference to the given []string and assigns it to the UserGroups field.
func (o *RbacManagerIdpUserGroupPost) SetUserGroups(v []string) {
	o.UserGroups = v
}

func (o RbacManagerIdpUserGroupPost) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UserGroups != nil {
		toSerialize["user_groups"] = o.UserGroups
	}
	return json.Marshal(toSerialize)
}

type NullableRbacManagerIdpUserGroupPost struct {
	value *RbacManagerIdpUserGroupPost
	isSet bool
}

func (v NullableRbacManagerIdpUserGroupPost) Get() *RbacManagerIdpUserGroupPost {
	return v.value
}

func (v *NullableRbacManagerIdpUserGroupPost) Set(val *RbacManagerIdpUserGroupPost) {
	v.value = val
	v.isSet = true
}

func (v NullableRbacManagerIdpUserGroupPost) IsSet() bool {
	return v.isSet
}

func (v *NullableRbacManagerIdpUserGroupPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRbacManagerIdpUserGroupPost(val *RbacManagerIdpUserGroupPost) *NullableRbacManagerIdpUserGroupPost {
	return &NullableRbacManagerIdpUserGroupPost{value: val, isSet: true}
}

func (v NullableRbacManagerIdpUserGroupPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRbacManagerIdpUserGroupPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


