/*
 * Anchore Enterprise Feeds
 *
 * Enterprise service for normalizing vulnerability data from external sources and making it available via API
 *
 * API version: 0.1.0
 * Contact: dev@anchore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feeds
// ServiceVersionService struct for ServiceVersionService
type ServiceVersionService struct {
	// Semantic Version string of the service implementation
	Version string `json:"version,omitempty"`
}
