/*
Anchore Experimental API

This is the Anchore Experiment API. Interfaces in this specification are unstable and will change in breaking ways between releases of Anchore Enterprise.

API version: 0.9.1
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package experimental

import (
	"encoding/json"
)

// checks if the AnchoreSummaryKubernetesClustersSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnchoreSummaryKubernetesClustersSummary{}

// AnchoreSummaryKubernetesClustersSummary struct for AnchoreSummaryKubernetesClustersSummary
type AnchoreSummaryKubernetesClustersSummary struct {
	ClustersCount *int32 `json:"clusters_count,omitempty"`
	NamespacesCount *int32 `json:"namespaces_count,omitempty"`
	TotalImages *int32 `json:"total_images,omitempty"`
	CompliantImages *int32 `json:"compliant_images,omitempty"`
	NonCompliantImages *int32 `json:"non_compliant_images,omitempty"`
	NotEvaluatedImages *int32 `json:"not_evaluated_images,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AnchoreSummaryKubernetesClustersSummary AnchoreSummaryKubernetesClustersSummary

// NewAnchoreSummaryKubernetesClustersSummary instantiates a new AnchoreSummaryKubernetesClustersSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnchoreSummaryKubernetesClustersSummary() *AnchoreSummaryKubernetesClustersSummary {
	this := AnchoreSummaryKubernetesClustersSummary{}
	return &this
}

// NewAnchoreSummaryKubernetesClustersSummaryWithDefaults instantiates a new AnchoreSummaryKubernetesClustersSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnchoreSummaryKubernetesClustersSummaryWithDefaults() *AnchoreSummaryKubernetesClustersSummary {
	this := AnchoreSummaryKubernetesClustersSummary{}
	return &this
}

// GetClustersCount returns the ClustersCount field value if set, zero value otherwise.
func (o *AnchoreSummaryKubernetesClustersSummary) GetClustersCount() int32 {
	if o == nil || IsNil(o.ClustersCount) {
		var ret int32
		return ret
	}
	return *o.ClustersCount
}

// GetClustersCountOk returns a tuple with the ClustersCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) GetClustersCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ClustersCount) {
		return nil, false
	}
	return o.ClustersCount, true
}

// HasClustersCount returns a boolean if a field has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) HasClustersCount() bool {
	if o != nil && !IsNil(o.ClustersCount) {
		return true
	}

	return false
}

// SetClustersCount gets a reference to the given int32 and assigns it to the ClustersCount field.
func (o *AnchoreSummaryKubernetesClustersSummary) SetClustersCount(v int32) {
	o.ClustersCount = &v
}

// GetNamespacesCount returns the NamespacesCount field value if set, zero value otherwise.
func (o *AnchoreSummaryKubernetesClustersSummary) GetNamespacesCount() int32 {
	if o == nil || IsNil(o.NamespacesCount) {
		var ret int32
		return ret
	}
	return *o.NamespacesCount
}

// GetNamespacesCountOk returns a tuple with the NamespacesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) GetNamespacesCountOk() (*int32, bool) {
	if o == nil || IsNil(o.NamespacesCount) {
		return nil, false
	}
	return o.NamespacesCount, true
}

// HasNamespacesCount returns a boolean if a field has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) HasNamespacesCount() bool {
	if o != nil && !IsNil(o.NamespacesCount) {
		return true
	}

	return false
}

// SetNamespacesCount gets a reference to the given int32 and assigns it to the NamespacesCount field.
func (o *AnchoreSummaryKubernetesClustersSummary) SetNamespacesCount(v int32) {
	o.NamespacesCount = &v
}

// GetTotalImages returns the TotalImages field value if set, zero value otherwise.
func (o *AnchoreSummaryKubernetesClustersSummary) GetTotalImages() int32 {
	if o == nil || IsNil(o.TotalImages) {
		var ret int32
		return ret
	}
	return *o.TotalImages
}

// GetTotalImagesOk returns a tuple with the TotalImages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) GetTotalImagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalImages) {
		return nil, false
	}
	return o.TotalImages, true
}

// HasTotalImages returns a boolean if a field has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) HasTotalImages() bool {
	if o != nil && !IsNil(o.TotalImages) {
		return true
	}

	return false
}

// SetTotalImages gets a reference to the given int32 and assigns it to the TotalImages field.
func (o *AnchoreSummaryKubernetesClustersSummary) SetTotalImages(v int32) {
	o.TotalImages = &v
}

// GetCompliantImages returns the CompliantImages field value if set, zero value otherwise.
func (o *AnchoreSummaryKubernetesClustersSummary) GetCompliantImages() int32 {
	if o == nil || IsNil(o.CompliantImages) {
		var ret int32
		return ret
	}
	return *o.CompliantImages
}

// GetCompliantImagesOk returns a tuple with the CompliantImages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) GetCompliantImagesOk() (*int32, bool) {
	if o == nil || IsNil(o.CompliantImages) {
		return nil, false
	}
	return o.CompliantImages, true
}

// HasCompliantImages returns a boolean if a field has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) HasCompliantImages() bool {
	if o != nil && !IsNil(o.CompliantImages) {
		return true
	}

	return false
}

// SetCompliantImages gets a reference to the given int32 and assigns it to the CompliantImages field.
func (o *AnchoreSummaryKubernetesClustersSummary) SetCompliantImages(v int32) {
	o.CompliantImages = &v
}

// GetNonCompliantImages returns the NonCompliantImages field value if set, zero value otherwise.
func (o *AnchoreSummaryKubernetesClustersSummary) GetNonCompliantImages() int32 {
	if o == nil || IsNil(o.NonCompliantImages) {
		var ret int32
		return ret
	}
	return *o.NonCompliantImages
}

// GetNonCompliantImagesOk returns a tuple with the NonCompliantImages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) GetNonCompliantImagesOk() (*int32, bool) {
	if o == nil || IsNil(o.NonCompliantImages) {
		return nil, false
	}
	return o.NonCompliantImages, true
}

// HasNonCompliantImages returns a boolean if a field has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) HasNonCompliantImages() bool {
	if o != nil && !IsNil(o.NonCompliantImages) {
		return true
	}

	return false
}

// SetNonCompliantImages gets a reference to the given int32 and assigns it to the NonCompliantImages field.
func (o *AnchoreSummaryKubernetesClustersSummary) SetNonCompliantImages(v int32) {
	o.NonCompliantImages = &v
}

// GetNotEvaluatedImages returns the NotEvaluatedImages field value if set, zero value otherwise.
func (o *AnchoreSummaryKubernetesClustersSummary) GetNotEvaluatedImages() int32 {
	if o == nil || IsNil(o.NotEvaluatedImages) {
		var ret int32
		return ret
	}
	return *o.NotEvaluatedImages
}

// GetNotEvaluatedImagesOk returns a tuple with the NotEvaluatedImages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) GetNotEvaluatedImagesOk() (*int32, bool) {
	if o == nil || IsNil(o.NotEvaluatedImages) {
		return nil, false
	}
	return o.NotEvaluatedImages, true
}

// HasNotEvaluatedImages returns a boolean if a field has been set.
func (o *AnchoreSummaryKubernetesClustersSummary) HasNotEvaluatedImages() bool {
	if o != nil && !IsNil(o.NotEvaluatedImages) {
		return true
	}

	return false
}

// SetNotEvaluatedImages gets a reference to the given int32 and assigns it to the NotEvaluatedImages field.
func (o *AnchoreSummaryKubernetesClustersSummary) SetNotEvaluatedImages(v int32) {
	o.NotEvaluatedImages = &v
}

func (o AnchoreSummaryKubernetesClustersSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnchoreSummaryKubernetesClustersSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClustersCount) {
		toSerialize["clusters_count"] = o.ClustersCount
	}
	if !IsNil(o.NamespacesCount) {
		toSerialize["namespaces_count"] = o.NamespacesCount
	}
	if !IsNil(o.TotalImages) {
		toSerialize["total_images"] = o.TotalImages
	}
	if !IsNil(o.CompliantImages) {
		toSerialize["compliant_images"] = o.CompliantImages
	}
	if !IsNil(o.NonCompliantImages) {
		toSerialize["non_compliant_images"] = o.NonCompliantImages
	}
	if !IsNil(o.NotEvaluatedImages) {
		toSerialize["not_evaluated_images"] = o.NotEvaluatedImages
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AnchoreSummaryKubernetesClustersSummary) UnmarshalJSON(data []byte) (err error) {
	varAnchoreSummaryKubernetesClustersSummary := _AnchoreSummaryKubernetesClustersSummary{}

	err = json.Unmarshal(data, &varAnchoreSummaryKubernetesClustersSummary)

	if err != nil {
		return err
	}

	*o = AnchoreSummaryKubernetesClustersSummary(varAnchoreSummaryKubernetesClustersSummary)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "clusters_count")
		delete(additionalProperties, "namespaces_count")
		delete(additionalProperties, "total_images")
		delete(additionalProperties, "compliant_images")
		delete(additionalProperties, "non_compliant_images")
		delete(additionalProperties, "not_evaluated_images")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAnchoreSummaryKubernetesClustersSummary struct {
	value *AnchoreSummaryKubernetesClustersSummary
	isSet bool
}

func (v NullableAnchoreSummaryKubernetesClustersSummary) Get() *AnchoreSummaryKubernetesClustersSummary {
	return v.value
}

func (v *NullableAnchoreSummaryKubernetesClustersSummary) Set(val *AnchoreSummaryKubernetesClustersSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableAnchoreSummaryKubernetesClustersSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableAnchoreSummaryKubernetesClustersSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnchoreSummaryKubernetesClustersSummary(val *AnchoreSummaryKubernetesClustersSummary) *NullableAnchoreSummaryKubernetesClustersSummary {
	return &NullableAnchoreSummaryKubernetesClustersSummary{value: val, isSet: true}
}

func (v NullableAnchoreSummaryKubernetesClustersSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnchoreSummaryKubernetesClustersSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


