/*
Anchore Experimental API

This is the Anchore Experiment API. Interfaces in this specification are unstable and will change in breaking ways between releases of Anchore Enterprise.

API version: 0.9.1
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package experimental

import (
	"encoding/json"
)

// checks if the SystemStatisticsDetailTwelveMonths type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStatisticsDetailTwelveMonths{}

// SystemStatisticsDetailTwelveMonths struct for SystemStatisticsDetailTwelveMonths
type SystemStatisticsDetailTwelveMonths struct {
	FirstDate *string `json:"first_date,omitempty"`
	LastDate *string `json:"last_date,omitempty"`
	Value *float32 `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SystemStatisticsDetailTwelveMonths SystemStatisticsDetailTwelveMonths

// NewSystemStatisticsDetailTwelveMonths instantiates a new SystemStatisticsDetailTwelveMonths object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStatisticsDetailTwelveMonths() *SystemStatisticsDetailTwelveMonths {
	this := SystemStatisticsDetailTwelveMonths{}
	return &this
}

// NewSystemStatisticsDetailTwelveMonthsWithDefaults instantiates a new SystemStatisticsDetailTwelveMonths object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStatisticsDetailTwelveMonthsWithDefaults() *SystemStatisticsDetailTwelveMonths {
	this := SystemStatisticsDetailTwelveMonths{}
	return &this
}

// GetFirstDate returns the FirstDate field value if set, zero value otherwise.
func (o *SystemStatisticsDetailTwelveMonths) GetFirstDate() string {
	if o == nil || IsNil(o.FirstDate) {
		var ret string
		return ret
	}
	return *o.FirstDate
}

// GetFirstDateOk returns a tuple with the FirstDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatisticsDetailTwelveMonths) GetFirstDateOk() (*string, bool) {
	if o == nil || IsNil(o.FirstDate) {
		return nil, false
	}
	return o.FirstDate, true
}

// HasFirstDate returns a boolean if a field has been set.
func (o *SystemStatisticsDetailTwelveMonths) HasFirstDate() bool {
	if o != nil && !IsNil(o.FirstDate) {
		return true
	}

	return false
}

// SetFirstDate gets a reference to the given string and assigns it to the FirstDate field.
func (o *SystemStatisticsDetailTwelveMonths) SetFirstDate(v string) {
	o.FirstDate = &v
}

// GetLastDate returns the LastDate field value if set, zero value otherwise.
func (o *SystemStatisticsDetailTwelveMonths) GetLastDate() string {
	if o == nil || IsNil(o.LastDate) {
		var ret string
		return ret
	}
	return *o.LastDate
}

// GetLastDateOk returns a tuple with the LastDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatisticsDetailTwelveMonths) GetLastDateOk() (*string, bool) {
	if o == nil || IsNil(o.LastDate) {
		return nil, false
	}
	return o.LastDate, true
}

// HasLastDate returns a boolean if a field has been set.
func (o *SystemStatisticsDetailTwelveMonths) HasLastDate() bool {
	if o != nil && !IsNil(o.LastDate) {
		return true
	}

	return false
}

// SetLastDate gets a reference to the given string and assigns it to the LastDate field.
func (o *SystemStatisticsDetailTwelveMonths) SetLastDate(v string) {
	o.LastDate = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SystemStatisticsDetailTwelveMonths) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatisticsDetailTwelveMonths) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SystemStatisticsDetailTwelveMonths) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *SystemStatisticsDetailTwelveMonths) SetValue(v float32) {
	o.Value = &v
}

func (o SystemStatisticsDetailTwelveMonths) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStatisticsDetailTwelveMonths) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstDate) {
		toSerialize["first_date"] = o.FirstDate
	}
	if !IsNil(o.LastDate) {
		toSerialize["last_date"] = o.LastDate
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SystemStatisticsDetailTwelveMonths) UnmarshalJSON(data []byte) (err error) {
	varSystemStatisticsDetailTwelveMonths := _SystemStatisticsDetailTwelveMonths{}

	err = json.Unmarshal(data, &varSystemStatisticsDetailTwelveMonths)

	if err != nil {
		return err
	}

	*o = SystemStatisticsDetailTwelveMonths(varSystemStatisticsDetailTwelveMonths)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "first_date")
		delete(additionalProperties, "last_date")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSystemStatisticsDetailTwelveMonths struct {
	value *SystemStatisticsDetailTwelveMonths
	isSet bool
}

func (v NullableSystemStatisticsDetailTwelveMonths) Get() *SystemStatisticsDetailTwelveMonths {
	return v.value
}

func (v *NullableSystemStatisticsDetailTwelveMonths) Set(val *SystemStatisticsDetailTwelveMonths) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStatisticsDetailTwelveMonths) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStatisticsDetailTwelveMonths) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStatisticsDetailTwelveMonths(val *SystemStatisticsDetailTwelveMonths) *NullableSystemStatisticsDetailTwelveMonths {
	return &NullableSystemStatisticsDetailTwelveMonths{value: val, isSet: true}
}

func (v NullableSystemStatisticsDetailTwelveMonths) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStatisticsDetailTwelveMonths) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


