/*
Anchore Experimental API

This is the Anchore Experiment API. Interfaces in this specification are unstable and will change in breaking ways between releases of Anchore Enterprise.

API version: 0.9.1
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package experimental

import (
	"encoding/json"
)

// checks if the AnchoreSummaryImageRepo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnchoreSummaryImageRepo{}

// AnchoreSummaryImageRepo a list of AnchoreSummaryImageRepoItem objects
type AnchoreSummaryImageRepo struct {
	Items []AnchoreSummaryImageRepoItem `json:"items,omitempty"`
	TotalRows *int32 `json:"total_rows,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AnchoreSummaryImageRepo AnchoreSummaryImageRepo

// NewAnchoreSummaryImageRepo instantiates a new AnchoreSummaryImageRepo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnchoreSummaryImageRepo() *AnchoreSummaryImageRepo {
	this := AnchoreSummaryImageRepo{}
	return &this
}

// NewAnchoreSummaryImageRepoWithDefaults instantiates a new AnchoreSummaryImageRepo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnchoreSummaryImageRepoWithDefaults() *AnchoreSummaryImageRepo {
	this := AnchoreSummaryImageRepo{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepo) GetItems() []AnchoreSummaryImageRepoItem {
	if o == nil || IsNil(o.Items) {
		var ret []AnchoreSummaryImageRepoItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepo) GetItemsOk() ([]AnchoreSummaryImageRepoItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepo) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []AnchoreSummaryImageRepoItem and assigns it to the Items field.
func (o *AnchoreSummaryImageRepo) SetItems(v []AnchoreSummaryImageRepoItem) {
	o.Items = v
}

// GetTotalRows returns the TotalRows field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepo) GetTotalRows() int32 {
	if o == nil || IsNil(o.TotalRows) {
		var ret int32
		return ret
	}
	return *o.TotalRows
}

// GetTotalRowsOk returns a tuple with the TotalRows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepo) GetTotalRowsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalRows) {
		return nil, false
	}
	return o.TotalRows, true
}

// HasTotalRows returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepo) HasTotalRows() bool {
	if o != nil && !IsNil(o.TotalRows) {
		return true
	}

	return false
}

// SetTotalRows gets a reference to the given int32 and assigns it to the TotalRows field.
func (o *AnchoreSummaryImageRepo) SetTotalRows(v int32) {
	o.TotalRows = &v
}

func (o AnchoreSummaryImageRepo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnchoreSummaryImageRepo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.TotalRows) {
		toSerialize["total_rows"] = o.TotalRows
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AnchoreSummaryImageRepo) UnmarshalJSON(data []byte) (err error) {
	varAnchoreSummaryImageRepo := _AnchoreSummaryImageRepo{}

	err = json.Unmarshal(data, &varAnchoreSummaryImageRepo)

	if err != nil {
		return err
	}

	*o = AnchoreSummaryImageRepo(varAnchoreSummaryImageRepo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "total_rows")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAnchoreSummaryImageRepo struct {
	value *AnchoreSummaryImageRepo
	isSet bool
}

func (v NullableAnchoreSummaryImageRepo) Get() *AnchoreSummaryImageRepo {
	return v.value
}

func (v *NullableAnchoreSummaryImageRepo) Set(val *AnchoreSummaryImageRepo) {
	v.value = val
	v.isSet = true
}

func (v NullableAnchoreSummaryImageRepo) IsSet() bool {
	return v.isSet
}

func (v *NullableAnchoreSummaryImageRepo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnchoreSummaryImageRepo(val *AnchoreSummaryImageRepo) *NullableAnchoreSummaryImageRepo {
	return &NullableAnchoreSummaryImageRepo{value: val, isSet: true}
}

func (v NullableAnchoreSummaryImageRepo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnchoreSummaryImageRepo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


