/*
Anchore Experimental API

This is the Anchore Experiment API. Interfaces in this specification are unstable and will change in breaking ways between releases of Anchore Enterprise.

API version: 0.9.1
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package experimental

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateSbomGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSbomGroupRequest{}

// CreateSbomGroupRequest struct for CreateSbomGroupRequest
type CreateSbomGroupRequest struct {
	Name string `json:"name" validate:"regexp=^(?!\\\\s*$).+"`
	Version string `json:"version" validate:"regexp=^(?!\\\\s*$).+"`
	Description *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateSbomGroupRequest CreateSbomGroupRequest

// NewCreateSbomGroupRequest instantiates a new CreateSbomGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSbomGroupRequest(name string, version string) *CreateSbomGroupRequest {
	this := CreateSbomGroupRequest{}
	this.Name = name
	this.Version = version
	return &this
}

// NewCreateSbomGroupRequestWithDefaults instantiates a new CreateSbomGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSbomGroupRequestWithDefaults() *CreateSbomGroupRequest {
	this := CreateSbomGroupRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateSbomGroupRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSbomGroupRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSbomGroupRequest) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *CreateSbomGroupRequest) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CreateSbomGroupRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CreateSbomGroupRequest) SetVersion(v string) {
	o.Version = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateSbomGroupRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSbomGroupRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateSbomGroupRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateSbomGroupRequest) SetDescription(v string) {
	o.Description = &v
}

func (o CreateSbomGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSbomGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSbomGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSbomGroupRequest := _CreateSbomGroupRequest{}

	err = json.Unmarshal(data, &varCreateSbomGroupRequest)

	if err != nil {
		return err
	}

	*o = CreateSbomGroupRequest(varCreateSbomGroupRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "version")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSbomGroupRequest struct {
	value *CreateSbomGroupRequest
	isSet bool
}

func (v NullableCreateSbomGroupRequest) Get() *CreateSbomGroupRequest {
	return v.value
}

func (v *NullableCreateSbomGroupRequest) Set(val *CreateSbomGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSbomGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSbomGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSbomGroupRequest(val *CreateSbomGroupRequest) *NullableCreateSbomGroupRequest {
	return &NullableCreateSbomGroupRequest{value: val, isSet: true}
}

func (v NullableCreateSbomGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSbomGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


