/*
Anchore Experimental API

This is the Anchore Experiment API. Interfaces in this specification are unstable and will change in breaking ways between releases of Anchore Enterprise.

API version: 0.9.1
Contact: dev@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package experimental

import (
	"encoding/json"
	"time"
)

// checks if the AnchoreSummaryImageRepoItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnchoreSummaryImageRepoItem{}

// AnchoreSummaryImageRepoItem struct for AnchoreSummaryImageRepoItem
type AnchoreSummaryImageRepoItem struct {
	Tag *string `json:"tag,omitempty"`
	AnalysisStatus *string `json:"analysis_status,omitempty"`
	ImageCount *int32 `json:"image_count,omitempty"`
	LatestTagDetectedAt *time.Time `json:"latest_tag_detected_at,omitempty"`
	ImageDigest *string `json:"image_digest,omitempty"`
	InventoryType *string `json:"inventory_type,omitempty"`
	LastSeen *time.Time `json:"last_seen,omitempty"`
	Context *string `json:"context,omitempty"`
	Alert *bool `json:"alert,omitempty"`
	AlertId *string `json:"alert_id,omitempty"`
	WatchTag *bool `json:"watch_tag,omitempty"`
	WatchTagId *string `json:"watch_tag_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AnchoreSummaryImageRepoItem AnchoreSummaryImageRepoItem

// NewAnchoreSummaryImageRepoItem instantiates a new AnchoreSummaryImageRepoItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnchoreSummaryImageRepoItem() *AnchoreSummaryImageRepoItem {
	this := AnchoreSummaryImageRepoItem{}
	return &this
}

// NewAnchoreSummaryImageRepoItemWithDefaults instantiates a new AnchoreSummaryImageRepoItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnchoreSummaryImageRepoItemWithDefaults() *AnchoreSummaryImageRepoItem {
	this := AnchoreSummaryImageRepoItem{}
	return &this
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *AnchoreSummaryImageRepoItem) SetTag(v string) {
	o.Tag = &v
}

// GetAnalysisStatus returns the AnalysisStatus field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetAnalysisStatus() string {
	if o == nil || IsNil(o.AnalysisStatus) {
		var ret string
		return ret
	}
	return *o.AnalysisStatus
}

// GetAnalysisStatusOk returns a tuple with the AnalysisStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetAnalysisStatusOk() (*string, bool) {
	if o == nil || IsNil(o.AnalysisStatus) {
		return nil, false
	}
	return o.AnalysisStatus, true
}

// HasAnalysisStatus returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasAnalysisStatus() bool {
	if o != nil && !IsNil(o.AnalysisStatus) {
		return true
	}

	return false
}

// SetAnalysisStatus gets a reference to the given string and assigns it to the AnalysisStatus field.
func (o *AnchoreSummaryImageRepoItem) SetAnalysisStatus(v string) {
	o.AnalysisStatus = &v
}

// GetImageCount returns the ImageCount field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetImageCount() int32 {
	if o == nil || IsNil(o.ImageCount) {
		var ret int32
		return ret
	}
	return *o.ImageCount
}

// GetImageCountOk returns a tuple with the ImageCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetImageCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ImageCount) {
		return nil, false
	}
	return o.ImageCount, true
}

// HasImageCount returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasImageCount() bool {
	if o != nil && !IsNil(o.ImageCount) {
		return true
	}

	return false
}

// SetImageCount gets a reference to the given int32 and assigns it to the ImageCount field.
func (o *AnchoreSummaryImageRepoItem) SetImageCount(v int32) {
	o.ImageCount = &v
}

// GetLatestTagDetectedAt returns the LatestTagDetectedAt field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetLatestTagDetectedAt() time.Time {
	if o == nil || IsNil(o.LatestTagDetectedAt) {
		var ret time.Time
		return ret
	}
	return *o.LatestTagDetectedAt
}

// GetLatestTagDetectedAtOk returns a tuple with the LatestTagDetectedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetLatestTagDetectedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LatestTagDetectedAt) {
		return nil, false
	}
	return o.LatestTagDetectedAt, true
}

// HasLatestTagDetectedAt returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasLatestTagDetectedAt() bool {
	if o != nil && !IsNil(o.LatestTagDetectedAt) {
		return true
	}

	return false
}

// SetLatestTagDetectedAt gets a reference to the given time.Time and assigns it to the LatestTagDetectedAt field.
func (o *AnchoreSummaryImageRepoItem) SetLatestTagDetectedAt(v time.Time) {
	o.LatestTagDetectedAt = &v
}

// GetImageDigest returns the ImageDigest field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetImageDigest() string {
	if o == nil || IsNil(o.ImageDigest) {
		var ret string
		return ret
	}
	return *o.ImageDigest
}

// GetImageDigestOk returns a tuple with the ImageDigest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetImageDigestOk() (*string, bool) {
	if o == nil || IsNil(o.ImageDigest) {
		return nil, false
	}
	return o.ImageDigest, true
}

// HasImageDigest returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasImageDigest() bool {
	if o != nil && !IsNil(o.ImageDigest) {
		return true
	}

	return false
}

// SetImageDigest gets a reference to the given string and assigns it to the ImageDigest field.
func (o *AnchoreSummaryImageRepoItem) SetImageDigest(v string) {
	o.ImageDigest = &v
}

// GetInventoryType returns the InventoryType field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetInventoryType() string {
	if o == nil || IsNil(o.InventoryType) {
		var ret string
		return ret
	}
	return *o.InventoryType
}

// GetInventoryTypeOk returns a tuple with the InventoryType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetInventoryTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InventoryType) {
		return nil, false
	}
	return o.InventoryType, true
}

// HasInventoryType returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasInventoryType() bool {
	if o != nil && !IsNil(o.InventoryType) {
		return true
	}

	return false
}

// SetInventoryType gets a reference to the given string and assigns it to the InventoryType field.
func (o *AnchoreSummaryImageRepoItem) SetInventoryType(v string) {
	o.InventoryType = &v
}

// GetLastSeen returns the LastSeen field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetLastSeen() time.Time {
	if o == nil || IsNil(o.LastSeen) {
		var ret time.Time
		return ret
	}
	return *o.LastSeen
}

// GetLastSeenOk returns a tuple with the LastSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetLastSeenOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSeen) {
		return nil, false
	}
	return o.LastSeen, true
}

// HasLastSeen returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasLastSeen() bool {
	if o != nil && !IsNil(o.LastSeen) {
		return true
	}

	return false
}

// SetLastSeen gets a reference to the given time.Time and assigns it to the LastSeen field.
func (o *AnchoreSummaryImageRepoItem) SetLastSeen(v time.Time) {
	o.LastSeen = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *AnchoreSummaryImageRepoItem) SetContext(v string) {
	o.Context = &v
}

// GetAlert returns the Alert field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetAlert() bool {
	if o == nil || IsNil(o.Alert) {
		var ret bool
		return ret
	}
	return *o.Alert
}

// GetAlertOk returns a tuple with the Alert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetAlertOk() (*bool, bool) {
	if o == nil || IsNil(o.Alert) {
		return nil, false
	}
	return o.Alert, true
}

// HasAlert returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasAlert() bool {
	if o != nil && !IsNil(o.Alert) {
		return true
	}

	return false
}

// SetAlert gets a reference to the given bool and assigns it to the Alert field.
func (o *AnchoreSummaryImageRepoItem) SetAlert(v bool) {
	o.Alert = &v
}

// GetAlertId returns the AlertId field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetAlertId() string {
	if o == nil || IsNil(o.AlertId) {
		var ret string
		return ret
	}
	return *o.AlertId
}

// GetAlertIdOk returns a tuple with the AlertId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetAlertIdOk() (*string, bool) {
	if o == nil || IsNil(o.AlertId) {
		return nil, false
	}
	return o.AlertId, true
}

// HasAlertId returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasAlertId() bool {
	if o != nil && !IsNil(o.AlertId) {
		return true
	}

	return false
}

// SetAlertId gets a reference to the given string and assigns it to the AlertId field.
func (o *AnchoreSummaryImageRepoItem) SetAlertId(v string) {
	o.AlertId = &v
}

// GetWatchTag returns the WatchTag field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetWatchTag() bool {
	if o == nil || IsNil(o.WatchTag) {
		var ret bool
		return ret
	}
	return *o.WatchTag
}

// GetWatchTagOk returns a tuple with the WatchTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetWatchTagOk() (*bool, bool) {
	if o == nil || IsNil(o.WatchTag) {
		return nil, false
	}
	return o.WatchTag, true
}

// HasWatchTag returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasWatchTag() bool {
	if o != nil && !IsNil(o.WatchTag) {
		return true
	}

	return false
}

// SetWatchTag gets a reference to the given bool and assigns it to the WatchTag field.
func (o *AnchoreSummaryImageRepoItem) SetWatchTag(v bool) {
	o.WatchTag = &v
}

// GetWatchTagId returns the WatchTagId field value if set, zero value otherwise.
func (o *AnchoreSummaryImageRepoItem) GetWatchTagId() string {
	if o == nil || IsNil(o.WatchTagId) {
		var ret string
		return ret
	}
	return *o.WatchTagId
}

// GetWatchTagIdOk returns a tuple with the WatchTagId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnchoreSummaryImageRepoItem) GetWatchTagIdOk() (*string, bool) {
	if o == nil || IsNil(o.WatchTagId) {
		return nil, false
	}
	return o.WatchTagId, true
}

// HasWatchTagId returns a boolean if a field has been set.
func (o *AnchoreSummaryImageRepoItem) HasWatchTagId() bool {
	if o != nil && !IsNil(o.WatchTagId) {
		return true
	}

	return false
}

// SetWatchTagId gets a reference to the given string and assigns it to the WatchTagId field.
func (o *AnchoreSummaryImageRepoItem) SetWatchTagId(v string) {
	o.WatchTagId = &v
}

func (o AnchoreSummaryImageRepoItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnchoreSummaryImageRepoItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.AnalysisStatus) {
		toSerialize["analysis_status"] = o.AnalysisStatus
	}
	if !IsNil(o.ImageCount) {
		toSerialize["image_count"] = o.ImageCount
	}
	if !IsNil(o.LatestTagDetectedAt) {
		toSerialize["latest_tag_detected_at"] = o.LatestTagDetectedAt
	}
	if !IsNil(o.ImageDigest) {
		toSerialize["image_digest"] = o.ImageDigest
	}
	if !IsNil(o.InventoryType) {
		toSerialize["inventory_type"] = o.InventoryType
	}
	if !IsNil(o.LastSeen) {
		toSerialize["last_seen"] = o.LastSeen
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Alert) {
		toSerialize["alert"] = o.Alert
	}
	if !IsNil(o.AlertId) {
		toSerialize["alert_id"] = o.AlertId
	}
	if !IsNil(o.WatchTag) {
		toSerialize["watch_tag"] = o.WatchTag
	}
	if !IsNil(o.WatchTagId) {
		toSerialize["watch_tag_id"] = o.WatchTagId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AnchoreSummaryImageRepoItem) UnmarshalJSON(data []byte) (err error) {
	varAnchoreSummaryImageRepoItem := _AnchoreSummaryImageRepoItem{}

	err = json.Unmarshal(data, &varAnchoreSummaryImageRepoItem)

	if err != nil {
		return err
	}

	*o = AnchoreSummaryImageRepoItem(varAnchoreSummaryImageRepoItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tag")
		delete(additionalProperties, "analysis_status")
		delete(additionalProperties, "image_count")
		delete(additionalProperties, "latest_tag_detected_at")
		delete(additionalProperties, "image_digest")
		delete(additionalProperties, "inventory_type")
		delete(additionalProperties, "last_seen")
		delete(additionalProperties, "context")
		delete(additionalProperties, "alert")
		delete(additionalProperties, "alert_id")
		delete(additionalProperties, "watch_tag")
		delete(additionalProperties, "watch_tag_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAnchoreSummaryImageRepoItem struct {
	value *AnchoreSummaryImageRepoItem
	isSet bool
}

func (v NullableAnchoreSummaryImageRepoItem) Get() *AnchoreSummaryImageRepoItem {
	return v.value
}

func (v *NullableAnchoreSummaryImageRepoItem) Set(val *AnchoreSummaryImageRepoItem) {
	v.value = val
	v.isSet = true
}

func (v NullableAnchoreSummaryImageRepoItem) IsSet() bool {
	return v.isSet
}

func (v *NullableAnchoreSummaryImageRepoItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnchoreSummaryImageRepoItem(val *AnchoreSummaryImageRepoItem) *NullableAnchoreSummaryImageRepoItem {
	return &NullableAnchoreSummaryImageRepoItem{value: val, isSet: true}
}

func (v NullableAnchoreSummaryImageRepoItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnchoreSummaryImageRepoItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


