/*
Anchore API

Testing SystemConfigurationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package enterprise

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/anchore/enterprise-client-go"
)

func Test_enterprise_SystemConfigurationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SystemConfigurationAPIService DeleteConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var configKey string

		httpRes, err := apiClient.SystemConfigurationAPI.DeleteConfiguration(context.Background(), configKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemConfigurationAPIService GetConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var configKey string

		resp, httpRes, err := apiClient.SystemConfigurationAPI.GetConfiguration(context.Background(), configKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemConfigurationAPIService GetConfigurationSchema", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SystemConfigurationAPI.GetConfigurationSchema(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemConfigurationAPIService ListConfigurations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SystemConfigurationAPI.ListConfigurations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemConfigurationAPIService PatchConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SystemConfigurationAPI.PatchConfiguration(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemConfigurationAPIService PutConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var configKey string

		resp, httpRes, err := apiClient.SystemConfigurationAPI.PutConfiguration(context.Background(), configKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
