/*
 * Anchore Enterprise Notifications API
 *
 * Enterprise API Managing Notifications
 *
 * API version: 1.0.1
 * Contact: dev@anchore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package 
// GitHubEndpointConfigurationAllOf struct for GitHubEndpointConfigurationAllOf
type GitHubEndpointConfigurationAllOf struct {
	// Github API endpoint, defaults to https://api.github.com if not specified
	Url string `json:"url,omitempty"`
	// GitHub username for creating issues
	Username string `json:"username"`
	// Personal access token for the GitHub account
	AccessToken string `json:"access_token"`
	// Owner of the repository to create issues against
	Owner string `json:"owner"`
	// Name of the repository to create issues against
	Repository string `json:"repository"`
	// Number of the milestone to associate with the issue
	Milestone int32 `json:"milestone,omitempty"`
	// List of labels to associate with the issue
	Labels []string `json:"labels,omitempty"`
	// List of user logins to assign to the issue.
	Assignees []string `json:"assignees,omitempty"`
}
